### PR TITLE
fixtureFilePath array

### PR DESCRIPTION
**Pull request by julesGoullee**
It's usefull to have multiple files, for split many data in differentes files, this PR have no regression, filePath can be an array of path or (like actually) just a string

### CODE REVIEW

**Comment by julesGoullee** [comment]
Why support node 4 & 6 , 8.9 in LST since november 2017

**Comment by rochejul** [comment]
Hi
I check at least forNodeJs 4.x because the NodeJs version fragmentation show there are still a lot of people using NodeJs less thant 6.x (nearly 30% if I remember). So this is important to check if it could work too on their side.

So please not use for the moment the "async" keyword (which is only a shortcut to generate a Promise)

Maybe I should put more documentation, but we already could load multiple file with using this syntax:

````js
sequelize_fixtures.loadFile('fixtures/*.json', models, {})
````
However, I will adapt the fixtureFilePath parameter to allow declare an array so use the following methods (instead made a for-loop):

````js
sequelize_fixtures.loadFiles(['fixtures/users.json', 'fixtures/data*.json'], models, {})
````
Could do create an enhancement ticket please ?

Many thanks

**Comment by rochejul** [comment]
Plus, Sequelize itself tries to be compatible with NodeJs 4.x: https://github.com/sequelize/sequelize/blob/master/package.json#L141

Regards

**Comment by julesGoullee** [comment]
Yep *.json it's not good, for respect sql contraint I need to insert data in the right order and sync

**Comment by rochejul** [comment]
Many thanks

Two feedbacks:
- You shoud update line https://github.com/rochejul/sequelize-mocking/blob/master/lib/sequelize-mocking.js#L109 to specify the update of the fixtureFilePath for the method createAndLoadFixtureFile
- Could you please add a unit test to check if we call welly the loadFiles method please ?

Many thanks again

Regards

**Comment by rochejul** [comment]
I will perte jour pull request this week-end ans update the documentation and unit test
Regards

**Comment by rochejul** [comment]
Many thanks: I have published on npm the 1.3.0-beta version with your updates

Regards

**Pull request merged**
