### PR TITLE
lodash library not imported anymore in Sequelize new versions

### PR DESCRIPTION
**Pull request by SuperToma**
With sequelize 4.8.0 (and greater) : Sequelize.Utils._ is undefined

### CODE REVIEW

**Comment by rochejul** [comment]
Hi
If so, you should too move lodash from devDependencies to dependencies into the package.json

Many thanks for your pull request

Regards

**Comment by SuperToma** [comment]
Lodash can't be a primary package with node 4.0.0 :( 
`Error: Cannot find module 'lodash'`

(no problem with node 6.x.x)

Do you need backward compatibility with node 4 ?

**Comment by rochejul** [comment]
Hi @SuperToma 
Can you regenerate the npm-shrinkwrap.json ? You can use the following command:

````
npm run generate-shrinkwrap
````

Otherwise, try to remove this file.

I very would like to have the same "constraints" as Sequelize (which is based on node >= 4).

If this does not work again, maybe we should look to replace the use of:
* _.merge (could be replace by https://github.com/schnittstabil/merge-options)
* _.isFunction

Otherwise, we can try to use instead underscore

Regards

**Comment by SuperToma** [comment]
I fixed it ! 
I ran `npm run generate-shrinkwrap`
Can you config npm-shrinkwrap.json ?

**Comment by rochejul** [comment]
Hi @SuperToma 
Sadly, the only thing we could specify when we generate this file is: should we include dependencies AND devDependencies, or only dependencies.

What did you expect around this configuration ?

I try to check your pull request tonight if possible)

Regards

**Comment by rochejul** [comment]
I could change it, but prefer the use of _.noop instead create onto the SequelizeMocking service a new method for that

Many thanks regards

**Comment by SuperToma** [comment]
Oups, 

1/ For the file "npm-shrinkwrap.json" I wanted to say : "Can you **check** the file npm-shrinkwrap.json" 
(instead of "can you config") because the the URLs changed in the file.

2/ For the noop function the problem is : 

- Lodash is not a sub-element of Sequelize anymore in new versions
- I first tried to load Lodash as a dependency (not dev-dependency) but this is not woking with node 4.x.x (works only with node >= 6)
- Then I replaced the 3 used Lodash functions to native functions :
  - _.merge : by Object.assign
  - _.isFunction : by typeOf === 'function'
  - _.partialRight : by adding options
  - _.noop : by creating a noop function (useful for tests)

Si je ne me trompe pas tu es français, ce serait peut-être plus simple pour communiquer :)

**Comment by rochejul** [comment]
The shrinkwrap file sounds good

Sure the _.noop is usefull for test. And as a node dependency, it will be available for testing. So into the test, we could do a require('lodash')

If you want I could apply the changes and check if it works

And yes I am french ☺

**Comment by SuperToma** [comment]
Lodash is still loaded as devDependency for tests inside /tests/ folder.
but _.noop was used in lib/sequelize-mocking.js that is build for production.

If you can apply the changes it would be wonderful :)
regards,

**Comment by rochejul** [comment]
Ok that means to declare it only as dependency.

I will create a ticket

Regards

**Comment by rochejul** [comment]
Related to #18 
Many thanks for your contribution

**Comment by SuperToma** [comment]
Wonderful, 
Thank you ! It works with Sequelize 4.14.0.

**Pull request closed without merging**
